<a href="https://colab.research.google.com/github/supriyapawar9500-cell/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
arr=np.array([10,20,35,45,50])
arr

array([10, 20, 35, 45, 50])

In [3]:
arr.shape

(5,)

In [4]:
arr.ndim

1

In [5]:
arr.sum()

np.int64(160)

In [6]:
result = np.where(arr>20)

In [7]:
print(result)

(array([2, 3, 4]),)

In [8]:
np.repeat(arr, 2)

array([10, 10, 20, 20, 35, 35, 45, 45, 50, 50])

In [9]:
np.tile(arr,2)

array([10, 20, 35, 45, 50, 10, 20, 35, 45, 50])

In [10]:
np.cumsum(arr)

array([ 10,  30,  65, 110, 160])

In [11]:
np.cumprod(arr)

array([      10,      200,     7000,   315000, 15750000])

In [13]:
result= np.argwhere(arr>15)

In [14]:
result

array([[1],
       [2],
       [3],
       [4]])

In [23]:
mask= np.logical_and(arr>20, arr<35)

In [24]:
arr[mask]
mask

array([False, False, False, False, False])

In [25]:
mask=np.logical_or(arr>10, arr<35)

In [26]:
mask

array([ True,  True,  True,  True,  True])

In [32]:
print(np.split(arr,1))

[array([10, 20, 35, 45, 50])]
